version: '3.8'

services:
  postgres:
    image: postgres:16.0-bullseye
    container_name: postgres
    environment:
      POSTGRES_DB: cinema_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinema-app-network
  app:
    build: .
    container_name: cinema-app
    ports:
      - "8086:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cinema_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - cinema-app-network

volumes:
  postgres_data:

networks:
  cinema-app-network:
