server:
  port: 8086
  error:
    include-stacktrace: never
    include-message: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema-app
    username: postgres
    password: 1928
  liquibase:
    change-log: liquibase/changelog-master.yml
    enabled: true
    drop-first: false
  jpa:
    properties:
      hibernate:
    open-in-view: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
